### ISSUE TITLE
Server middleware always creates Redux store, even if other middlewares handle the request

### ISSUE THREAD

**Issue by PAkerstrand** [rocjs/roc-package-web-app-react#9] opened 2016-04-26 19:38 UTC
Following the [discussion here](https://github.com/rocjs/roc-package-web-app-react/pull/7#discussion_r61125126), we should come up with a way to only create the redux store if the request is not handled by another middleware.

**Comment by ab-core-boxfuse** [comment] 2016-07-07 11:35
Another thing we'd like to have is a way to run middleware after the react render. So there seems to be three places were you may want to hook in:
- Before the store is created: If the request is handled here we don't need to create the store or render react.
- After the store is created, but before react rendering: Here state that's needed for rendering can be added to the store.
- After react rendering: Middleware that needs to look at the store in the state it was when rendering can be run here.

**Comment by dentrado** [comment] 2016-07-07 11:37
Another thing we'd like to have is a way to run middleware after the react render. So there seems to be three places were you may want to hook in:
- Before the store is created: If the request is handled here we don't need to create the store or render react.
- After the store is created, but before react rendering: Here state that's needed for rendering can be added to the store.
- After react rendering: Middleware that needs to look at the store in the state it was when rendering can be run here.

**Comment by dentrado** [comment] 2016-10-05 08:41
@dlmr Has there been any updates to this with 1.0? Specifically we would like to run middleware after react rendering, so we can access redux state that's fetched with redial.

**Comment by lizell** [comment] 2016-10-05 08:47
The case in particular that I would love to be able to do is something like:

```
<Route
            path="/live-sport"
            httpHeaders={{ 'Cache-Control': 'max-age=5' }}
            .../>
```

And then in a middleware:

``` js
...
const { getState } = this.state.reduxStore;
const { routeProps: { httpHeaders } = {} } = getState();
...
```

given that we populate our state with some `routeProps`. It seams like a very straight forward way of setting different HTTP headers based on routing.

In order to be able to access the state after the React rendering has started we would need some hook or entry point we do not currently have, right?

**Comment by dlmr** [comment] 2016-10-05 21:29
@dentrado Not as of yet, but this is something that will be addressed soon now that the core almost is completed.

@lizell Yes, we do need a new pattern to manage this. You can opt-out of the default server entry point to work around this but the change needed to avoid this should be quite small and easy to implement. We still need a generic way to manage things like the case you mentions but another alternative could be to use something like `<ServerStatus>` to manage `httpHeaders`.

**Comment by lizell** [comment] 2016-10-06 09:09
@dlmr with opting out, you mean roll my own? Otherwise the `<ServerStatus>` only handles the status code, not arbitrary headers (but works as an example of course). The problem is that I would still need to be able to hook in to the code somewhere after the react rendering, so I'd still need to roll my own server entry point, right?

**Comment by lizell** [comment] 2016-10-06 09:10
On the other hand all things™ could be solved more easily once we have time to address the root issue(s)! ;)

**Comment by dlmr** [comment] 2018-01-02 10:38
Closing for now since there are workarounds that work fine, primarily taking over the server entry point.

Please open a new issue in https://github.com/rocjs/extensions if this is something that should be addressed soon and that if this is still a problem.

**Closed as completed by dlmr** 2018-01-02 10:38 UTC
Labels: enhancement, help wanted
